# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/Ui_UserWindow.ui'
#
# Created: Wed Apr 16 19:10:53 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_UserWindow(object):
    def setupUi(self, UserWindow):
        UserWindow.setObjectName("UserWindow")
        UserWindow.resize(410, 526)
        self.centralwidget = QtGui.QWidget(UserWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.main_tw = QtGui.QTabWidget(self.centralwidget)
        self.main_tw.setObjectName("main_tw")
        self.stats_tab = QtGui.QWidget()
        self.stats_tab.setObjectName("stats_tab")
        self.gridLayout_2 = QtGui.QGridLayout(self.stats_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.improve_btn = QtGui.QPushButton(self.stats_tab)
        self.improve_btn.setObjectName("improve_btn")
        self.gridLayout_2.addWidget(self.improve_btn, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.stats_tv = QtGui.QTableView(self.stats_tab)
        self.stats_tv.setObjectName("stats_tv")
        self.gridLayout_2.addWidget(self.stats_tv, 0, 0, 1, 2)
        self.main_tw.addTab(self.stats_tab, "")
        self.settings_tab = QtGui.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.gridLayout_3 = QtGui.QGridLayout(self.settings_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.snippets_gb = QtGui.QGroupBox(self.settings_tab)
        self.snippets_gb.setObjectName("snippets_gb")
        self.gridLayout_6 = QtGui.QGridLayout(self.snippets_gb)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 1, 0, 1, 1)
        self.snippets_tv = QtGui.QTableView(self.snippets_gb)
        self.snippets_tv.setObjectName("snippets_tv")
        self.gridLayout_6.addWidget(self.snippets_tv, 0, 0, 1, 3)
        self.add_snippet_btn = QtGui.QPushButton(self.snippets_gb)
        self.add_snippet_btn.setObjectName("add_snippet_btn")
        self.gridLayout_6.addWidget(self.add_snippet_btn, 1, 2, 1, 1)
        self.remove_snippet_btn = QtGui.QPushButton(self.snippets_gb)
        self.remove_snippet_btn.setObjectName("remove_snippet_btn")
        self.gridLayout_6.addWidget(self.remove_snippet_btn, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.snippets_gb, 3, 0, 1, 2)
        self.shortcuts_gb = QtGui.QGroupBox(self.settings_tab)
        self.shortcuts_gb.setObjectName("shortcuts_gb")
        self.gridLayout_4 = QtGui.QGridLayout(self.shortcuts_gb)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.shortcuts_tv = QtGui.QTableView(self.shortcuts_gb)
        self.shortcuts_tv.setObjectName("shortcuts_tv")
        self.gridLayout_4.addWidget(self.shortcuts_tv, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.shortcuts_gb, 2, 0, 1, 2)
        self.general_gb = QtGui.QGroupBox(self.settings_tab)
        self.general_gb.setObjectName("general_gb")
        self.gridLayout_7 = QtGui.QGridLayout(self.general_gb)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem2, 1, 3, 1, 1)
        self.label = QtGui.QLabel(self.general_gb)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 0, 2, 1, 1)
        self.nw_pos_combo = QtGui.QComboBox(self.general_gb)
        self.nw_pos_combo.setObjectName("nw_pos_combo")
        self.gridLayout_7.addWidget(self.nw_pos_combo, 1, 2, 1, 1)
        self.gridLayout_3.addWidget(self.general_gb, 1, 0, 1, 2)
        self.main_tw.addTab(self.settings_tab, "")
        self.playground_tab = QtGui.QWidget()
        self.playground_tab.setObjectName("playground_tab")
        self.gridLayout_5 = QtGui.QGridLayout(self.playground_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.playground_te = QtGui.QTextEdit(self.playground_tab)
        self.playground_te.setObjectName("playground_te")
        self.gridLayout_5.addWidget(self.playground_te, 0, 0, 1, 1)
        self.main_tw.addTab(self.playground_tab, "")
        self.gridLayout.addWidget(self.main_tw, 0, 0, 1, 1)
        UserWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(UserWindow)
        self.statusbar.setObjectName("statusbar")
        UserWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(UserWindow)
        self.toolBar.setObjectName("toolBar")
        UserWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLogout = QtGui.QAction(UserWindow)
        self.actionLogout.setObjectName("actionLogout")

        self.retranslateUi(UserWindow)
        self.main_tw.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(UserWindow)
        UserWindow.setTabOrder(self.main_tw, self.stats_tv)
        UserWindow.setTabOrder(self.stats_tv, self.shortcuts_tv)
        UserWindow.setTabOrder(self.shortcuts_tv, self.snippets_tv)
        UserWindow.setTabOrder(self.snippets_tv, self.playground_te)

    def retranslateUi(self, UserWindow):
        UserWindow.setWindowTitle(QtGui.QApplication.translate("UserWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.improve_btn.setText(QtGui.QApplication.translate("UserWindow", "Improve...", None, QtGui.QApplication.UnicodeUTF8))
        self.main_tw.setTabText(self.main_tw.indexOf(self.stats_tab), QtGui.QApplication.translate("UserWindow", "Usage Stats", None, QtGui.QApplication.UnicodeUTF8))
        self.snippets_gb.setTitle(QtGui.QApplication.translate("UserWindow", "Snippets", None, QtGui.QApplication.UnicodeUTF8))
        self.add_snippet_btn.setText(QtGui.QApplication.translate("UserWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.remove_snippet_btn.setText(QtGui.QApplication.translate("UserWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.shortcuts_gb.setTitle(QtGui.QApplication.translate("UserWindow", "Shortcuts", None, QtGui.QApplication.UnicodeUTF8))
        self.general_gb.setTitle(QtGui.QApplication.translate("UserWindow", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("UserWindow", "Notifications", None, QtGui.QApplication.UnicodeUTF8))
        self.main_tw.setTabText(self.main_tw.indexOf(self.settings_tab), QtGui.QApplication.translate("UserWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.main_tw.setTabText(self.main_tw.indexOf(self.playground_tab), QtGui.QApplication.translate("UserWindow", "Playground", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("UserWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLogout.setText(QtGui.QApplication.translate("UserWindow", "Log Out", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLogout.setToolTip(QtGui.QApplication.translate("UserWindow", "Log Out", None, QtGui.QApplication.UnicodeUTF8))

